# Generated by Django 4.0.5 on 2022-06-06 03:01

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, null=True, unique=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(max_length=32)),
                ('time_send_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_shop', models.FileField(max_length=255, null=True, upload_to=users.models.upload_shop)),
                ('shop_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('hash_password', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('img_buyer', models.FileField(max_length=255, null=True, upload_to=users.models.upload_user)),
                ('user_id_facebook', models.CharField(max_length=32, null=True, unique=True)),
                ('shop', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.shop')),
            ],
        ),
    ]
