# Generated by Django 4.0.5 on 2022-06-06 03:01

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_image', models.FileField(max_length=255, null=True, upload_to=categories.models.upload_category)),
                ('shop', models.ManyToManyField(related_name='category', to='users.shop')),
            ],
        ),
    ]
