# Generated by Django 4.0.5 on 2022-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shop',
            field=models.ManyToManyField(to='users.shop'),
        ),
    ]
