# Generated by Django 4.0.5 on 2022-06-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Product_Image',
        ),
    ]
