# Generated by Django 4.0.5 on 2022-07-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
